version: "3.8"

services:
  web:
    image: php:8.1-apache
    container_name: gestion_restaurantes_web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      # Indica a Apache que use el directorio 'public' como DocumentRoot
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    restart: unless-stopped